name: JMeter Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  jmeter-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
	  distribution: 'temurin'
          java-version: '11'

      - name: Install JMeter
        run: sudo apt-get update && sudo apt-get install -y jmeter

      - name: Run JMeter tests
        run: |
          jmeter -n -t non-functional-test/terheleses_teszt.jmx -l non-functional-test/Eredmenyek/results.jtl

      - name: Upload JMeter results
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results
          path: results/results.jtl
